package constants

var (
	ENV_JWT_SECRET = "JWT_SECRET"

	ENV_LOG_OUTPUT = "LOG_OUTPUT"
	ENV_LOG_LEVEL  = "LOG_LEVEL"

	ENV_MONGO_URL             = "MONGO_URL"
	ENV_MONGO_DB              = "MONGO_DB"
	ENV_MONGO_COLLECTION_USER = "MONGO_COLLECTION_USER"
)
